### ISSUE TITLE
Experiencing a browser crash while using fixed tile width and when the component is collapsed

### ISSUE THREAD

**Issue by puneetg1983** [sheikalthaf/ngu-carousel#21]
I am trying to use this component in a collapsible container and when the component is collapsed, it is causing chrome to crash because of this line of code

`this.pointIndex = Math.ceil(Nos / this.data.slideItems);`

What is happening is that `this.data.slideItems` has value zero which causes `this.pointIndex` to have an infinite value and the loop just after this runs forever and causes the crash.

The problem is happening in case of fixed width tile scenarios and only when they are collapsed because in that case the below statement assigns this.data.items to 0 as  this.data.carouselWidth is zero because the component is in a collapsed state

`this.data.items = Math.trunc(
        this.data.carouselWidth / this.userData.grid.all`

and that causes the below piece of code to assign this.data.slideItems to zero

`this.data.slideItems = +(this.userData.slide < this.data.items
      ? this.userData.slide
      : this.data.items);`

(In my case userData.slide was 1 but this.data.items turned out to be zero)

It was a bit hard to track in my application as I am trying to reuse your component multiple times on a page and expanding \ collapsing based on user choice.

Hoping this makes sense and that the fix is easy and it is available soon...

**Comment by sheikalthaf** [comment]
Hi,

Anyway to reproduce this bug. If possible please create a stackblitz.

**Comment by puneetg1983** [comment]
Here you go https://stackblitz.com/edit/angular-xqiqkm

uncomment line 16,17 30, 31 to see the chrome crash in app.component.html to see the browser crash

hope this helps

**Comment by puneetg1983** [comment]
For some reason the SAVE wasnt working on stackblitz, luckily I had the sample saved [angular-xqiqkm.zip](https://github.com/sheikalthaf/ngu-carousel/files/1771406/angular-xqiqkm.zip)

so this should help you repro....

**Comment by sheikalthaf** [comment]
Thanks for the source. I will check and update the carousel.

**Comment by puneetg1983** [comment]
Even got it on stackblitz - https://stackblitz.com/edit/angular-x2m3xa?file=app/app.component.html

**Comment by puneetg1983** [comment]
@sheikalthaf - first of all, I must say this is one of the best carousel's for Angular that I came across so thanks !!!

Unfortunately due to this bug, we cannot use this component. May be it is too much to ask but can I know if you can fix it soon and release an update ?

**Comment by sheikalthaf** [comment]
@puneetg1983 I will try my best

**Comment by puneetg1983** [comment]
Any updates?

**Comment by sheikalthaf** [comment]
I found the error. Oninit the carousel width gets zero. It is a serious issue. I will try to fix this weakend.

**Comment by puneetg1983** [comment]
Perfect !!! 

Would appreciate if you could generate a package too with the fix that we can refer....

**Comment by puneetg1983** [comment]
Any luck with this ?

**Comment by niteshluharuka** [comment]
Awaiting a fix for this..

**Comment by sheikalthaf** [comment]
Hi @puneetg1983 @niteshluharuka 

Really sorry for delay fix I have fixed the issue now take a look at this [release](https://github.com/sheikalthaf/ngu-carousel/releases/tag/v1.4.9-beta-2)

**Comment by mhosman** [comment]
Is still crashing. Just add some carousel's, resize the page many times...... CRASH

**Comment by sheikalthaf** [comment]
@mhosman @puneetg1983 Updated the carousel to latest version. Please check
